### ISSUE TITLE
GO 1.7.x support

### ISSUE THREAD

**Issue by FrenchBen** [docker/infrakit#276]
Looks like `make ci` doesn't work with GO 1.7.3.

## Output
```
$ make ci
+ fmt
+ vet
panic: inconsistent import:
	var net/http.DefaultTransport net/http.RoundTripper
previously imported as:
	var DefaultTransport net/http.RoundTripper
 [recovered]
	panic: inconsistent import:
	var net/http.DefaultTransport net/http.RoundTripper
previously imported as:
	var DefaultTransport net/http.RoundTripper


goroutine 1 [running]:
panic(0x2734c0, 0xc42016f2f0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
go/types.(*Checker).handleBailout(0xc4200162a0, 0xc4203758d8)
	/usr/local/Cellar/go/1.7.3/libexec/src/go/types/check.go:213 +0xae
panic(0x2734c0, 0xc42016f2f0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:458 +0x243
go/internal/gcimporter.(*importer).declare(0xc42015c000, 0x3f54a0, 0xc420115130)
	/usr/local/Cellar/go/1.7.3/libexec/src/go/internal/gcimporter/bimport.go:175 +0x17c
go/internal/gcimporter.(*importer).obj(0xc42015c000, 0xfffffffffffffffc)
	/usr/local/Cellar/go/1.7.3/libexec/src/go/internal/gcimporter/bimport.go:195 +0x1b4
go/internal/gcimporter.BImportData(0xc42000afc0, 0xc4205fc000, 0x1cd653, 0x1ffe00, 0xc42000f871, 0x8, 0x0, 0x8, 0x0, 0x0)
	/usr/local/Cellar/go/1.7.3/libexec/src/go/internal/gcimporter/bimport.go:88 +0x390
go/internal/gcimporter.Import(0xc42000afc0, 0xc42000f871, 0x8, 0x7fff5fbff4b5, 0x14, 0xc4203a5090, 0x0, 0x0)
	/usr/local/Cellar/go/1.7.3/libexec/src/go/internal/gcimporter/gcimporter.go:166 +0x551
go/importer.gcimports.ImportFrom(0xc42000afc0, 0xc42000f871, 0x8, 0x7fff5fbff4b5, 0x14, 0x0, 0xc4203a5450, 0x0, 0x0)
	/usr/local/Cellar/go/1.7.3/libexec/src/go/importer/importer.go:70 +0x67
go/types.(*Checker).collectObjects(0xc4200162a0)
	/usr/local/Cellar/go/1.7.3/libexec/src/go/types/resolver.go:191 +0x826
go/types.(*Checker).checkFiles(0xc4200162a0, 0xc420162bc0, 0x2, 0x2, 0x0, 0x0)
	/usr/local/Cellar/go/1.7.3/libexec/src/go/types/check.go:225 +0xaa
go/types.(*Checker).Files(0xc4200162a0, 0xc420162bc0, 0x2, 0x2, 0xc420155f20, 0xc4200cb960)
	/usr/local/Cellar/go/1.7.3/libexec/src/go/types/check.go:218 +0x49
go/types.(*Config).Check(0xc420161900, 0xc42000f808, 0x4, 0xc420013d40, 0xc420162bc0, 0x2, 0x2, 0xc4201662d0, 0x0, 0xc4200001a0, ...)
	/usr/local/Cellar/go/1.7.3/libexec/src/go/types/api.go:344 +0x1a3
main.(*Package).check(0xc42006c8a0, 0xc420013d40, 0xc420162bc0, 0x2, 0x2, 0xc420162bd0, 0x1)
	/usr/local/Cellar/go/1.7.3/libexec/src/cmd/vet/types.go:76 +0x370
main.doPackage(0x2cd704, 0x1, 0xc42000a2b0, 0x2, 0x2, 0x0, 0x1)
	/usr/local/Cellar/go/1.7.3/libexec/src/cmd/vet/main.go:336 +0x999
main.main()
	/usr/local/Cellar/go/1.7.3/libexec/src/cmd/vet/main.go:244 +0x345
exit status 2
plugin/flavor/swarm/flavor.go:182: arg nodes for printf verb %s of wrong type: []github.com/docker/infrakit/vendor/github.com/docker/docker/api/types/swarm.Node
exit status 1
plugin/group/quorum.go:101: range variable unknownInstance captured by func literal
exit status 1
make: *** [vet] Error 1
```

**Comment by wfarner** [comment]
Looks good from where i sit:
```shell
$ go version
go version go1.7.3 darwin/amd64
$ git rev-parse HEAD
d260ac8d9de23a2cae28f22daf19d7788eaf06bd
$ make ci >/dev/null && echo pass || echo fail
pass
```

Seems potentially related to https://github.com/golang/go/issues/16112

Apparently `go install` can fix this by updating stale `.o` files.  I believe i've also addressed it in the past with `rm -r $GOPATH/pkg`, but i suggest you do your own research on side-effects of deleting that directory...i did it in a moment of desperation :-)

**Comment by FrenchBen** [comment]
Cleaning out old pkgs did it for me as well - Thanks!
