### ISSUE TITLE
vmware-instance plugin

### ISSUE THREAD

**Issue by bdeluca** [docker/infrakit#618]
@thebsdbox 

trying this the first time, with following definition (don't know the correct word for that). There is no folder for test-ik on the vmware vsphere client. I also tested it with an empty test folder, same issue. 

```
{
  "ID": "test-ik",
  "Plugin": "group",
  "Properties": {
    "Allocation": {
      "Size": 1
    },
    "Instance": {
      "Plugin": "instance-vsphere",
      "Properties": {
        "Datastore": "vsanDatastore",
        "Network": "VM Network",
        "Hostname": "localhost.localdomain",
        "isoPath": "linuxkit/linuxkit.iso",
        "CPUs": "1",
        "MEM": "512",
        "vmPrefix": "lk",
        "powerOn": true
      }
    },
    "Flavor": {
      "Plugin": "flavor-vanilla",
      "Properties": {
        "Init": [
          "sudo apt-get update -y",
          "sudo apt-get install -y nginx",
          "sudo service nginx start"
        ],
        "Tags": {
          "tier": "web",
          "project": "infrakit"
        }
      }
    }
  }
}
```

I  receive this error. 

```
ik group commit test1.json 
{
    "address": "/home/bdeluca/.infrakit/plugins/flavor-swarm",
    "lvl": 4,
    "module": "discovery/local",
    "msg": "Discovered plugin",
    "stack": "[github.com/docker/infrakit/pkg/discovery/local/dir.go:150 github.com/docker/infrakit/pkg/discovery/local/dir.go:69 group/main.go:51 github.com/docker/infrakit/pkg/plugin/group/group.go:239 github.com/docker/infrakit/pkg/plugin/group/group.go:57 github.com/docker/infrakit/pkg/rpc/group/service.go:50 runtime/asm_amd64.s:515 reflect/value.go:434 reflect/value.go:302 github.com/docker/infrakit/vendor/github.com/gorilla/rpc/v2/server.go:142 github.com/docker/infrakit/pkg/rpc/server/server.go:61 \u003cautogenerated\u003e:5 github.com/docker/infrakit/vendor/github.com/gorilla/mux/mux.go:114]",
    "t": "2017-07-05T12:30:30.713848969+03:00"
}
{
    "address": "/home/bdeluca/.infrakit/plugins/flavor-vanilla",
    "lvl": 4,
    "module": "discovery/local",
    "msg": "Discovered plugin",
    "stack": "[github.com/docker/infrakit/pkg/discovery/local/dir.go:150 github.com/docker/infrakit/pkg/discovery/local/dir.go:69 group/main.go:51 github.com/docker/infrakit/pkg/plugin/group/group.go:239 github.com/docker/infrakit/pkg/plugin/group/group.go:57 github.com/docker/infrakit/pkg/rpc/group/service.go:50 runtime/asm_amd64.s:515 reflect/value.go:434 reflect/value.go:302 github.com/docker/infrakit/vendor/github.com/gorilla/rpc/v2/server.go:142 github.com/docker/infrakit/pkg/rpc/server/server.go:61 \u003cautogenerated\u003e:5 github.com/docker/infrakit/vendor/github.com/gorilla/mux/mux.go:114]",
    "t": "2017-07-05T12:30:30.714040095+03:00"
}
{
    "address": "/home/bdeluca/.infrakit/plugins/group",
    "lvl": 4,
    "module": "discovery/local",
    "msg": "Discovered plugin",
    "stack": "[github.com/docker/infrakit/pkg/discovery/local/dir.go:150 github.com/docker/infrakit/pkg/discovery/local/dir.go:69 group/main.go:51 github.com/docker/infrakit/pkg/plugin/group/group.go:239 github.com/docker/infrakit/pkg/plugin/group/group.go:57 github.com/docker/infrakit/pkg/rpc/group/service.go:50 runtime/asm_amd64.s:515 reflect/value.go:434 reflect/value.go:302 github.com/docker/infrakit/vendor/github.com/gorilla/rpc/v2/server.go:142 github.com/docker/infrakit/pkg/rpc/server/server.go:61 \u003cautogenerated\u003e:5 github.com/docker/infrakit/vendor/github.com/gorilla/mux/mux.go:114]",
    "t": "2017-07-05T12:30:30.714150334+03:00"
}
{
    "address": "/home/bdeluca/.infrakit/plugins/instance-vsphere",
    "lvl": 4,
    "module": "discovery/local",
    "msg": "Discovered plugin",
    "stack": "[github.com/docker/infrakit/pkg/discovery/local/dir.go:150 github.com/docker/infrakit/pkg/discovery/local/dir.go:69 group/main.go:51 github.com/docker/infrakit/pkg/plugin/group/group.go:239 github.com/docker/infrakit/pkg/plugin/group/group.go:57 github.com/docker/infrakit/pkg/rpc/group/service.go:50 runtime/asm_amd64.s:515 reflect/value.go:434 reflect/value.go:302 github.com/docker/infrakit/vendor/github.com/gorilla/rpc/v2/server.go:142 github.com/docker/infrakit/pkg/rpc/server/server.go:61 \u003cautogenerated\u003e:5 github.com/docker/infrakit/vendor/github.com/gorilla/mux/mux.go:114]",
    "t": "2017-07-05T12:30:30.714262554+03:00"
}
{
    "address": "/home/bdeluca/.infrakit/plugins/flavor-swarm",
    "lvl": 4,
    "module": "discovery/local",
    "msg": "Discovered plugin",
    "stack": "[github.com/docker/infrakit/pkg/discovery/local/dir.go:150 github.com/docker/infrakit/pkg/discovery/local/dir.go:69 group/main.go:43 github.com/docker/infrakit/pkg/plugin/group/group.go:248 github.com/docker/infrakit/pkg/plugin/group/group.go:57 github.com/docker/infrakit/pkg/rpc/group/service.go:50 runtime/asm_amd64.s:515 reflect/value.go:434 reflect/value.go:302 github.com/docker/infrakit/vendor/github.com/gorilla/rpc/v2/server.go:142 github.com/docker/infrakit/pkg/rpc/server/server.go:61 \u003cautogenerated\u003e:5 github.com/docker/infrakit/vendor/github.com/gorilla/mux/mux.go:114]",
    "t": "2017-07-05T12:30:30.715486302+03:00"
}
{
    "address": "/home/bdeluca/.infrakit/plugins/flavor-vanilla",
    "lvl": 4,
    "module": "discovery/local",
    "msg": "Discovered plugin",
    "stack": "[github.com/docker/infrakit/pkg/discovery/local/dir.go:150 github.com/docker/infrakit/pkg/discovery/local/dir.go:69 group/main.go:43 github.com/docker/infrakit/pkg/plugin/group/group.go:248 github.com/docker/infrakit/pkg/plugin/group/group.go:57 github.com/docker/infrakit/pkg/rpc/group/service.go:50 runtime/asm_amd64.s:515 reflect/value.go:434 reflect/value.go:302 github.com/docker/infrakit/vendor/github.com/gorilla/rpc/v2/server.go:142 github.com/docker/infrakit/pkg/rpc/server/server.go:61 \u003cautogenerated\u003e:5 github.com/docker/infrakit/vendor/github.com/gorilla/mux/mux.go:114]",
    "t": "2017-07-05T12:30:30.715647186+03:00"
}
{
    "address": "/home/bdeluca/.infrakit/plugins/group",
    "lvl": 4,
    "module": "discovery/local",
    "msg": "Discovered plugin",
    "stack": "[github.com/docker/infrakit/pkg/discovery/local/dir.go:150 github.com/docker/infrakit/pkg/discovery/local/dir.go:69 group/main.go:43 github.com/docker/infrakit/pkg/plugin/group/group.go:248 github.com/docker/infrakit/pkg/plugin/group/group.go:57 github.com/docker/infrakit/pkg/rpc/group/service.go:50 runtime/asm_amd64.s:515 reflect/value.go:434 reflect/value.go:302 github.com/docker/infrakit/vendor/github.com/gorilla/rpc/v2/server.go:142 github.com/docker/infrakit/pkg/rpc/server/server.go:61 \u003cautogenerated\u003e:5 github.com/docker/infrakit/vendor/github.com/gorilla/mux/mux.go:114]",
    "t": "2017-07-05T12:30:30.715779141+03:00"
}
{
    "address": "/home/bdeluca/.infrakit/plugins/instance-vsphere",
    "lvl": 4,
    "module": "discovery/local",
    "msg": "Discovered plugin",
    "stack": "[github.com/docker/infrakit/pkg/discovery/local/dir.go:150 github.com/docker/infrakit/pkg/discovery/local/dir.go:69 group/main.go:43 github.com/docker/infrakit/pkg/plugin/group/group.go:248 github.com/docker/infrakit/pkg/plugin/group/group.go:57 github.com/docker/infrakit/pkg/rpc/group/service.go:50 runtime/asm_amd64.s:515 reflect/value.go:434 reflect/value.go:302 github.com/docker/infrakit/vendor/github.com/gorilla/rpc/v2/server.go:142 github.com/docker/infrakit/pkg/rpc/server/server.go:61 \u003cautogenerated\u003e:5 github.com/docker/infrakit/vendor/github.com/gorilla/mux/mux.go:114]",
    "t": "2017-07-05T12:30:30.715906993+03:00"
}
INFO[2939] Committing group test-ik (pretend=false)     
Committed test-ik: Managing 1 instances
bdeluca@mubuntudesk:~/PycharmProjects/ifrakit_play/test$ 2017/07/05 12:30:30 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 845 [running]:
net/http.(*conn).serve.func1(0xc4201ea320)
	/usr/lib/go-1.8/src/net/http/server.go:1721 +0xd0
panic(0xd16580, 0x16047b0)
	/usr/lib/go-1.8/src/runtime/panic.go:489 +0x2cf
main.returnDataFromAnnotation(0x15d5440, 0xc420224300, 0xc4204a07c0, 0xef09d2, 0x5, 0x0, 0x0)
	/home/bdeluca/go/src/github.com/docker/infrakit/pkg/provider/vsphere/vsphere.go:262 +0x1e3
main.findInstancesFromAnnotation(0x15d5440, 0xc420224300, 0xc4202b66c0, 0xc4203d8380, 0x7, 0x0, 0x0, 0x0, 0x15cb6c0, 0xc42048fac0)
	/home/bdeluca/go/src/github.com/docker/infrakit/pkg/provider/vsphere/vsphere.go:284 +0x101
main.findGroupInstances(0xc4202295c0, 0xc4203d8380, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/bdeluca/go/src/github.com/docker/infrakit/pkg/provider/vsphere/vsphere.go:252 +0x6e7
main.(*plugin).DescribeInstances(0xc4202295c0, 0xc4202b6600, 0xc5ad00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/bdeluca/go/src/github.com/docker/infrakit/pkg/provider/vsphere/plugin.go:174 +0x1fc
github.com/docker/infrakit/pkg/rpc/instance.(*Instance).DescribeInstances(0xc4202295e0, 0xc420358800, 0xc4203f43e0, 0xc4202b6630, 0x0, 0x0)
	/home/bdeluca/go/src/github.com/docker/infrakit/pkg/rpc/instance/service.go:162 +0x87
reflect.Value.call(0xc420073200, 0xc42000e158, 0x13, 0xeefa31, 0x4, 0xc420057a38, 0x4, 0x4, 0xc4202b6630, 0xed70e0, ...)
	/usr/lib/go-1.8/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xc420073200, 0xc42000e158, 0x13, 0xc420057a38, 0x4, 0x4, 0x0, 0x13, 0xc420086000)
	/usr/lib/go-1.8/src/reflect/value.go:302 +0xa4
github.com/docker/infrakit/vendor/github.com/gorilla/rpc/v2.(*Server).ServeHTTP(0xc42011fcf0, 0x15d4180, 0xc420224280, 0xc420358800)
	/home/bdeluca/go/src/github.com/docker/infrakit/vendor/github.com/gorilla/rpc/v2/server.go:142 +0x453
github.com/docker/infrakit/pkg/rpc/server.loggingHandler.ServeHTTP(0x15cb480, 0xc42011fcf0, 0x15d4b00, 0xc42024e2a0, 0xc420358800)
	/home/bdeluca/go/src/github.com/docker/infrakit/pkg/rpc/server/server.go:61 +0x19c
github.com/docker/infrakit/pkg/rpc/server.(*loggingHandler).ServeHTTP(0xc42027e2e0, 0x15d4b00, 0xc42024e2a0, 0xc420358800)
	<autogenerated>:5 +0x74
github.com/docker/infrakit/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420019720, 0x15d4b00, 0xc42024e2a0, 0xc420358800)
	/home/bdeluca/go/src/github.com/docker/infrakit/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
net/http.serverHandler.ServeHTTP(0xc4200b5600, 0x15d4b00, 0xc42024e2a0, 0xc420358500)
	/usr/lib/go-1.8/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4201ea320, 0x15d5440, 0xc420224000)
	/usr/lib/go-1.8/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/lib/go-1.8/src/net/http/server.go:2668 +0x2ce
```

**Comment by thebsdbox** [comment]
This error points to line 262, where we split a string by newline `\n`. If a VM isn't found then this string won't be allocated, resulting in a null pointer being accessed. This has been addressed in PR #617

**Comment by bdeluca** [comment]
right I had the docker/infrakit.git checked out in the standard place and a copy with your patch in different directory. When I tried to build your version, it build the other one :( 

with your patch applied I get a new error

```
INFO[0099] Adding 1 instances to group to reach desired 1 
2017/07/05 15:12:54 http: panic serving @: interface conversion: interface {} is string, not float64
goroutine 76 [running]:
net/http.(*conn).serve.func1(0xc4202dc8c0)
	/usr/lib/go-1.8/src/net/http/server.go:1721 +0xd0
panic(0xd31960, 0xc420272b80)
	/usr/lib/go-1.8/src/runtime/panic.go:489 +0x2cf
main.parseParameters(0xc4200145d0, 0xc420205860, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/bdeluca/go/src/github.com/docker/infrakit/pkg/provider/vsphere/vsphere.go:171 +0x80d
main.(*plugin).Provision(0xc420205860, 0xc42040fa40, 0xc420014570, 0xc4202ae6e0, 0x4d, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/bdeluca/go/src/github.com/docker/infrakit/pkg/provider/vsphere/plugin.go:95 +0xc2
github.com/docker/infrakit/pkg/rpc/instance.(*Instance).Provision(0xc420205880, 0xc420221e00, 0xc4202ae690, 0xc42040fb40, 0x0, 0x0)
	/home/bdeluca/go/src/github.com/docker/infrakit/pkg/rpc/instance/service.go:117 +0x9b
reflect.Value.call(0xc420228980, 0xc4202080a0, 0x13, 0xef0a34, 0x4, 0xc420173a38, 0x4, 0x4, 0xc42040fb40, 0xed80e0, ...)
	/usr/lib/go-1.8/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xc420228980, 0xc4202080a0, 0x13, 0xc420173a38, 0x4, 0x4, 0x0, 0x1c, 0xc420328000)
	/usr/lib/go-1.8/src/reflect/value.go:302 +0xa4
github.com/docker/infrakit/vendor/github.com/gorilla/rpc/v2.(*Server).ServeHTTP(0xc4202131f0, 0x15d6180, 0xc420272b40, 0xc420221e00)
	/home/bdeluca/go/src/github.com/docker/infrakit/vendor/github.com/gorilla/rpc/v2/server.go:142 +0x453
github.com/docker/infrakit/pkg/rpc/server.loggingHandler.ServeHTTP(0x15cd480, 0xc4202131f0, 0x15d6b00, 0xc4202321c0, 0xc420221e00)
	/home/bdeluca/go/src/github.com/docker/infrakit/pkg/rpc/server/server.go:61 +0x19c
github.com/docker/infrakit/pkg/rpc/server.(*loggingHandler).ServeHTTP(0xc4202137d0, 0x15d6b00, 0xc4202321c0, 0xc420221e00)
	<autogenerated>:5 +0x74
github.com/docker/infrakit/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202027d0, 0x15d6b00, 0xc4202321c0, 0xc420221e00)
	/home/bdeluca/go/src/github.com/docker/infrakit/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
net/http.serverHandler.ServeHTTP(0xc42022e630, 0x15d6b00, 0xc4202321c0, 0xc420221c00)
	/usr/lib/go-1.8/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4202dc8c0, 0x15d7440, 0xc420483d40)
	/usr/lib/go-1.8/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/lib/go-1.8/src/net/http/server.go:2668 +0x2ce
ERRO[0099] Failed to provision: Post http://h: EOF      

```

**Comment by thebsdbox** [comment]
I assume in your yaml cpus is "1" instead of 1. I need to fix that. It needs to be a number not a string.

**Comment by bdeluca** [comment]
yes :) you got there just as I did

**Comment by thebsdbox** [comment]
I appreciate your testing though. Clearly a few things that need tidying up.

**Comment by bdeluca** [comment]
almost there I think, 

WARN[0033] No Instances found                           
INFO[0032] Adding 1 instances to group to reach desired 1 
ERRO[0033] Error: 
vSphere host [localhost.localdomain], could not be found 


this now.

**Comment by thebsdbox** [comment]
Haha, well at least we're now on actual errors and not programming issues. You need to specify an actual vSphere host to create the VM on. I presume something like esxi01.lab etc. Whatever the host names are in vCenter.

**Comment by bdeluca** [comment]
oh right, that doesn't quite fit with the vsphere concept. It makes more sense to specify a cluster and a resource pool.

**Comment by thebsdbox** [comment]
Turns out the VMware API needs a host to first provision the VM on... then DRS will schedule it to start somewhere.

**Comment by bdeluca** [comment]
Can you check the hosts for a cluster and pick one (randomly) ? If I fired up a lot of machines it wouldnt make sense to do it on a single host.

I tried starting 10, I now have about 30 vms on the host, none are running its trying to delete extras, configure some and start them. But pretty much mass failure.

**Comment by thebsdbox** [comment]
In theory you would use DRS to load balance new VMs. I can look at adding in code to find a suitable host. Bus even in the vCenter UI you still need to select your deployment target (host). Are you using a bootable ISO? As I mentioned it is aimed at linuxkit today and I'll add in support for templates when I'm back from annual leave.

**Comment by bdeluca** [comment]
oh got there but the vsphere interface was behind. My cluster is pretty slow

**Comment by bdeluca** [comment]
at one point it had created 44 virtual machines. Then lots of attempts to delete, and power off.

**Comment by bdeluca** [comment]
So playing around it a little bit more, it can take a while to stabilise, possibly be less aggressive about starting new VM's if they are not there yet? I noticed a race where if you destroy the group before the it is stable then vm's are missed for destruction

**Comment by bdeluca** [comment]
I left it for a little while and came back and my plugin was un-authenticated

**Comment by thebsdbox** [comment]
If you had destroyed all VMs then the vSphere  plugin won't be asked anything by the group plugin, this means that the session will end. 

In theory if you're using the plugin you're managing instances. If we continuously re-auth it feels like a security risk. I'm not 100% sure on the best solution at the moment. 

On a side note can you detail versions and hardware setup for your VMware cluster as I never came across race issues powering on etc.

**Comment by bdeluca** [comment]
The cluster is running vsphere/esxi 6.0, 3 nodes 2x6 cpu 48gigs ram, But the disk is vsan and its slow, I have only 250gb ssd cache and 2x2TB disks per node, its completely unsupported (works fine though).

**Comment by bdeluca** [comment]
whats the security situation with the other providers? aws etc?

**Comment by thebsdbox** [comment]
The vSphere plugin has been re-implemented with a Stateful watcher, this means that when it provisions on unsupported infrastructure (i.e. no storage acceleration) the stat will be handled by the plugin until vSphere returns with a provisioned virtual machine 

#759 

This has been tested on a vCenter cluster with backend storage with VAAI/VAPI and simple local storage. (please re-open if there are any other issues)
