### ISSUE TITLE
Panic occurs starting ingress controller

### ISSUE THREAD

**Issue by craigyam** [docker/infrakit#781]
Going through the example in the docs/controller/ingress directory.
Execute:
`INFRAKIT_MANAGER_BACKEND=swarm infrakit plugin start manager simulator ingress group vanilla vars combo`
followed by:
`infrakit ingress controller commit -y ./example.yml`
The command fails with:
`CRIT[11-29|20:50:15] error executing                          module=main cmd=infrakit err="Post http://h: EOF" fn=main.main
Post http://h: EOF`

Looking in the logs I see a panic:
```
2017/11/29 20:50:15 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 1082 [running]:
net/http.(*conn).serve.func1(0xc42078d5e0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x2751880, 0x458f650)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/docker/infrakit/pkg/controller/internal.(*Controller).leaderGuard(0xc4204f4d00, 0x260ac40, 0x7d4400)
	/home/sddev/workspace/go/src/github.com/docker/infrakit/pkg/controller/internal/controller.go:59 +0x2a
github.com/docker/infrakit/pkg/controller/internal.(*Controller).Commit(0xc4204f4d00, 0x0, 0xc420226af0, 0x7, 0x0, 0x0, 0x0, 0xc420226b60, 0x8, 0xc4207406c0, ...)
	/home/sddev/workspace/go/src/github.com/docker/infrakit/pkg/controller/internal/controller.go:140 +0x95
github.com/docker/infrakit/pkg/rpc/controller.(*Controller).Commit.func1(0x2a24400, 0xc4204f4d00, 0x2, 0xc420736900)
	/home/sddev/workspace/go/src/github.com/docker/infrakit/pkg/rpc/controller/service.go:97 +0xd1
github.com/docker/infrakit/pkg/rpc/internal.(*Keyed).Do(0xc4204af610, 0x45bc700, 0xc42072c750, 0xc42074d380, 0x0, 0x0)
	/home/sddev/workspace/go/src/github.com/docker/infrakit/pkg/rpc/internal/keyed.go:61 +0x38f
github.com/docker/infrakit/pkg/rpc/controller.(*Controller).Commit(0xc4204af618, 0xc42072ae00, 0xc42072c750, 0xc42078dae0, 0x0, 0x0)
	/home/sddev/workspace/go/src/github.com/docker/infrakit/pkg/rpc/controller/service.go:102 +0x76
reflect.Value.call(0xc420199600, 0xc4204af628, 0x13, 0x2cd6ac9, 0x4, 0xc42074d870, 0x4, 0x4, 0xc42078dae0, 0x2c543c0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xc420199600, 0xc4204af628, 0x13, 0xc42074d870, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/docker/infrakit/vendor/github.com/gorilla/rpc/v2.(*Server).ServeHTTP(0xc4202d60d0, 0x45db080, 0xc4206cb3c0, 0xc42072ae00)
	/home/sddev/workspace/go/src/github.com/docker/infrakit/vendor/github.com/gorilla/rpc/v2/server.go:142 +0x453
github.com/docker/infrakit/pkg/rpc/server.loggingHandler.ServeHTTP(0x45bd4c0, 0xc4202d60d0, 0x0, 0x0, 0x0, 0xc4202be960, 0x25, 0x45e4f40, 0xc42069dc00, 0xc42072ae00)
	/home/sddev/workspace/go/src/github.com/docker/infrakit/pkg/rpc/server/server.go:70 +0x38f
github.com/docker/infrakit/pkg/rpc/server.(*loggingHandler).ServeHTTP(0xc4204f5240, 0x45e4f40, 0xc42069dc00, 0xc42072ae00)
	<autogenerated>:5 +0x87
github.com/docker/infrakit/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201459f0, 0x45e4f40, 0xc42069dc00, 0xc42072ae00)
	/home/sddev/workspace/go/src/github.com/docker/infrakit/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
net/http.serverHandler.ServeHTTP(0xc4202eab00, 0x45e4f40, 0xc42069dc00, 0xc42072ac00)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42078d5e0, 0x45e66c0, 0xc4206cb000)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce```
This was working with commit `6dfe702d8566fec6f024b31b13ea5fc9c1f89e6e`

**Comment by chungers** [comment]
Yes the changes to the RPC interfaces broke this.  Working on it.

**Comment by chungers** [comment]
@craigyam  - there's a work-around...  There's a problem with the ordering in which the plugins are started.  Until I fixed the issue, you can avoid the panic by making sure that `manager` and `group` start up first, before `ingress`.  This is because `ingress` controller depends on the `manager` properly running and `manager` in turn depends on `group` plugin.   So in your startup sequence, `ingress` came before `group` which causes the panic because the `manager` was still waiting for the `group` plugin.

Let me know if the work-around works for you.  I will leave this open until the issue is fully addressed.

**Comment by craigyam** [comment]
Thanks @chungers that worked.
